
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programleftPLUSMINUSleftMULTDIVASSIGN DIV ELSE ID IF INT LBRACE LPAREN MAIN MINUS MULT NUMBER PLUS RBRACE RETURN RPAREN SEMI WHILEprogram : INT MAIN LPAREN RPAREN LBRACE stmt_list RBRACEstmt_list : stmt\n                 | stmt_list stmtstmt : INT ID ASSIGN expr SEMIstmt : RETURN expr SEMIexpr : expr PLUS exprexpr : expr MINUS exprexpr : NUMBERexpr : ID'
    
_lr_action_items = {'INT':([0,6,8,9,13,18,24,],[2,7,7,-2,-3,-5,-4,]),'$end':([1,12,],[0,-1,]),'MAIN':([2,],[3,]),'LPAREN':([3,],[4,]),'RPAREN':([4,],[5,]),'LBRACE':([5,],[6,]),'RETURN':([6,8,9,13,18,24,],[10,10,-2,-3,-5,-4,]),'ID':([7,10,17,19,20,],[11,16,16,16,16,]),'RBRACE':([8,9,13,18,24,],[12,-2,-3,-5,-4,]),'NUMBER':([10,17,19,20,],[15,15,15,15,]),'ASSIGN':([11,],[17,]),'SEMI':([14,15,16,21,22,23,],[18,-8,-9,24,-6,-7,]),'PLUS':([14,15,16,21,22,23,],[19,-8,-9,19,-6,-7,]),'MINUS':([14,15,16,21,22,23,],[20,-8,-9,20,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'stmt_list':([6,],[8,]),'stmt':([6,8,],[9,13,]),'expr':([10,17,19,20,],[14,21,22,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> INT MAIN LPAREN RPAREN LBRACE stmt_list RBRACE','program',7,'p_program','parser.py',21),
  ('stmt_list -> stmt','stmt_list',1,'p_stmt_list','parser.py',25),
  ('stmt_list -> stmt_list stmt','stmt_list',2,'p_stmt_list','parser.py',26),
  ('stmt -> INT ID ASSIGN expr SEMI','stmt',5,'p_stmt_decl','parser.py',33),
  ('stmt -> RETURN expr SEMI','stmt',3,'p_stmt_return','parser.py',37),
  ('expr -> expr PLUS expr','expr',3,'p_expr_plus','parser.py',41),
  ('expr -> expr MINUS expr','expr',3,'p_expr_minus','parser.py',45),
  ('expr -> NUMBER','expr',1,'p_expr_number','parser.py',49),
  ('expr -> ID','expr',1,'p_expr_id','parser.py',53),
]
